apis/urls.py
from django.urls import path
from rest_framework.routers import DefaultRouter
from .views import  ChatViewSet, CurrentChatView, CurrentUserView, UserViewSet, PostViewSet, CurrentPostView, CommentViewSet, CurrentCommentView, CurrentEventView, EventViewSet, EventsCommentsViewSet, CurrentEventsCommentsView, LiveViewSet, CurrentLiveView

router = DefaultRouter()
router.register('users', UserViewSet, basename='users')
router.register('posts', PostViewSet, basename='posts')
router.register('comments', CommentViewSet, basename='comments')
router.register('events', EventViewSet, basename='events')
router.register('eventscomments', EventsCommentsViewSet, basename='eventscomments')
router.register('chat', ChatViewSet, basename='chat')
router.register('live', LiveViewSet, basename='live')

urlpatterns = router.urls + [
    path('currentuser/', CurrentUserView.as_view()),
    path('currentpost/', CurrentPostView.as_view()),
    path('currentcomment/', CurrentCommentView.as_view()),
    path('currentevent/', CurrentEventView.as_view()),
    path('currenteventscomments/', CurrentEventsCommentsView.as_view()),
    path('currentchat/', CurrentChatView.as_view()),
    path('currentlive/', CurrentLiveView.as_view()),
]  

kosupure/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
    path('apis/v1/', include('apis.urls')),
    path('api-auth/', include('rest_framework.urls')),
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('events/', TemplateView.as_view(template_name='events.html'), name='events'),
    path('game/', TemplateView.as_view(template_name='game.html'), name='game'),
    path('board/', TemplateView.as_view(template_name='board.html'), name='board'),
    path('calculator/', TemplateView.as_view(template_name='calculator.html'), name='calculator')
]

users/urls.py
from django.urls import path
from .views import SignUpView

app_name = 'users'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

templates/board.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap CSS -->
    {% comment %} <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> {% endcomment %}
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Chatroom</title>
</head>

<body>
{% csrf_token %}
{% if user.is_authenticated %}
    <header class="header">
        <h1>Welcome to Kosupure, {{ user.username }}!</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
        <hr class="tophr">
    </header>
    <span><a style="font-size: 1.5em" href="{% url 'logout' %}">Logout</a></span>
{% else %}
    <header class="header">
        <h1>Welcome to Kosupure, visitor!</h1>
        <h1>You are not logged in.</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
    </header>
    <span><a href="{% url 'login' %}">Login</a> <a href="{% url 'users:signup' %}" >Sign Up</a></span>
        <br>
        <hr>
        <br>
        <h1>You must log-in to participate</h1>
        <hr>
        <br>
        <br>
    </header>
{% endif %}

<div id="chatroom">
    <youtube-live :go_live='go_live' :user='user' :csrf_token='csrf_token'></youtube-live>
    <div class="row">
        <div class="col-md-12">
            <div class="panel-body">
                <center>
                    <h1>Superhero Live!</h1>
                </center>
            
                <br>
                <div v-if='user.id' class="row">
                    <div class="col-md-12">
                        <div class="panel panel-default">
                            <div class="panel-body">
                                <strong>Interact Here:</strong><br>
                                <input type="text" class="form-control" style="margin-bottom: 10px" placeholder="Enter your message..."  v-model="msg" v-on:keyup.enter="submitChat">
                                <button class="btn btn-primary btn" @click="submitChat">
                                    Send Message
                                    <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div>
                    <button @click="deleteChat">Click here to clean chatroom</button>
                </div>    
                <div class="panel panel-default" style="height: 700px; overflow: auto; border: black solid 2px; background-color: lightblue;" id="chat-content">
                        <div v-for="m in chat" class="chatback">
                            <div style="margin-bottom: 10px">
                                <span>[[ m.chat_name.username ]]:  </span>
                                <span v-html="m.message"></span>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </div>

</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>


Vue.component('youtube-live', {
    dilemiters: ['[[', ']]'],
    props: ['csrf_token', 'user'],
    data: function () {
        return {
        live_video: '',
        video_list: [],
        latest_live: '',
        }
    },
    template: `
    <div>
        <form v-if="user.is_creator">
            <input type="text" size='75' placeholder="youtube livestream ending (everything after 'https://youtu.be/') ie NsJRsvkkuC0 " v-model="live_video">
            <button @click="submitLive">Submit Live</button>
        </form>
        <center>
            <iframe 
                width="375" 
                height="200" 
                class="embed-responsive-item" 
                :src="latest_live"
                allowfullscreen>
            </iframe>
        </center>
        <br>
    </div>
    `,
    methods: {
        submitLive: function () {
            if (this.live_video.length > 0){
            axios({
                method: 'post',
                url: '/apis/v1/live/',
                headers: {
                    'X-CSRFToken': this.csrf_token
                },
                data: {
                    "site": this.live_video
                }
            }).then(response => {
                loadLive()
            })
        }},
        loadLive: function () {
            axios({
                method: 'get',
                url: '/apis/v1/live/'
            }).then(response => {
                this.video_list = response.data.reverse()
                this.latest_live = "https://www.youtube.com/embed/" + this.video_list[0]['site']
            })
        }
    },
    mounted: function () {
        this.loadLive()
    }
})

        let part1= "https://www.youtube.com/embed/"
        let part2= "6KwOld751DE"
        let part3= part1.concat(part2)

    const app = new Vue({
        el: "#chatroom",
        delimiters: ['[[', ']]'],
        data: {
            user: [],
            csrf_token: '',
            name: '',
            msg: '',
            chat: [],
            time: (new Date()).toLocaleTimeString(),
        },
        methods: {
            loadCurrentUser: function() {
                axios({
                    method: 'get',
                    url: '/apis/v1/currentuser/'
                }).then(response => {
                    this.user = response.data
                    this.name = this.user.username
                })
            },
            deleteChat: function (){
                this.chat = ''
            },
            loadChat: function () {
                axios({
                    method: 'GET',
                    url: '/apis/v1/chat/'
                }).then(response => {
                    this.chat = response.data
                    this.scrollBottom()
                })
            },
            submitChat: function (post) {
                if (this.msg.length > 0){
                    axios({
                        method: 'post',
                        url: '/apis/v1/chat/',
                        headers: {
                            'X-CSRFToken': this.csrf_token
                        },
                        data: {
                                "message": this.msg,
                                "name": this.user.id
                        }
                    }).then(response => {
                        this.msg = ''
                        this.loadChat()
                    })
                }},
            scrollBottom(){
                Vue.nextTick(function () {
                    var div = document.getElementById("chat-content")
                    div.scrollTop = div.scrollHeight
                })
            }
        },
        mounted: function () {
            this.csrf_token = document.querySelector("input[name=csrfmiddlewaretoken]").value
            this.loadCurrentUser()
            this.loadChat()
        },
        watch: {
            msg: function(){
                var banned = ["fuck", "shit", "pussy", "vagina", "penis", "ass", "Ass", "@ss", "Shit", "Fuck", "Damn", "damn", "asshole", "Asshole",
                "Fat", "fat", "tit", "Tit", "Tits", "tits", "fUck", "fuCk", "fucK", "dick", "Dick", "whore", "Whore", "politics", "BLM", "hate", "Hate", "retard"]
                for (var i = 0; i < banned.length; i++) {
                    if (this.msg.includes(banned[i])) {
                        this.msg = this.msg.replace(banned[i], "*".repeat(banned[i].length)) //sets the input to * times the length of the banned word
                    }
                }
            }
        }
    })



</script>
</body>

templates/calculator.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Calculator</title>
</head>

<body>
{% csrf_token %}
{% if user.is_authenticated %}
    <header class="header">
        <h1>Welcome to Kosupure, {{ user.username }}!</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
        <hr class="tophr">
    </header>
    <span><a style="font-size: 1.5em" href="{% url 'logout' %}">Logout</a></span>
{% else %}
    <header class="header">
        <h1>Welcome to Kosupure, visitor!</h1>
        <h1>You are not logged in.</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
    </header>
    <span><a href="{% url 'login' %}">Login</a> <a href="{% url 'users:signup' %}" >Sign Up</a></span>
{% endif %}

<div id="calculator">

<h1>How much Cosplay can I afford?</h1>
<div class="wrapper">
    <div class="justify-content-center align-items-center">
        <div>
            <canvas id="myChart"></canvas>
        </div>
    </div>
</div>
<kos-life></kos-life>

</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

    Vue.component('kos-life', {
        delimiters: ['[[', ']]'],
        data: function () {
            return {
                conhotel: '',
                contravel: '',
                confood: '',
                conextras: '',
                contotal: '',
                rent: '',
                vehicle: '',
                food: '',
                entertainment: '',
                hometotal: '',
                leftover: '',
                money: '',
                cosplaymonies: '',
            }
        },
        template: `
        <div>
            <form>
                <h2>The Convention Expenses:</h2>
                <p>Hotel Costs:
                    <input type="text" size="50" placeholder='Hotel (usually $250-$300/night)' v-model="conhotel">
                </p>
                <p>Travel Costs:
                    <input type="text" size="50" placeholder='Travel (usually $75-$200)' v-model="contravel">
                </p>
                <p>Food Costs:
                    <input type="text" size="50" placeholder='Food/Beer (usually $50/person/day)' v-model="confood">
                </p>
                <p>Con Extras:
                    <input type="text" size="50" placeholder='Art/Autographs/Photos/Parties (usually $400)' v-model="conextras">
                </p>
                <br>
                <center>
                    <button @click.prevent="conmath">Calculate Convention Total</button>
                    <h3>Convention Total: $[[ contotal ]]</h3>
                </center>
            </form>
            <form v-if="contotal > 0">
                <h2>Life (Per Month):</h2>
                <p>Rent:
                    <input type="text" size="50" placeholder='Rent (usually $1000-2300/month)' v-model="rent">
                </p>
                <p>Food:
                    <input type="text" size="50" placeholder='Dining in/out (usually $400-700/month)' v-model="food">
                </p>
                <p>Vehicle:
                    <input type="text" size="50" placeholder='Car/Gas/Insurance (usually $300-900/month)' v-model="vehicle">
                </p>
                <p>Entertainment:
                    <input type="text" size="50" placeholder='Movies/Comics/Games (usually $300-900/month)' v-model="entertainment">
                </p>
                <br>
                <center>
                    <button @click.prevent="homemath">Calculate Living Expenses</button>
                    <h3>Living Expenses (12 Months): $[[ hometotal ]]</h3>
                    <h1>Total Cost thus far: $[[ leftover ]]</h1>
                </center>
            </form>
            <br>
            <br>
            <form v-if="leftover > 0">
                <p>Annual Earnings after taxes: <input type="text" size="25" placeholder="No commas, ie 26000" v-model="money"></p>
                <center>
                    <button @click.prevent="cosplaymoney">Calculate Money for Cosplay</button>
                    <h1>Money for Cosplay: $[[ cosplaymonies ]]</h1>
                </center>
            </form>
        </div>
        `,
        methods: {
            conmath: function () {
                this.contotal = parseInt(this.conhotel) + parseInt(this.contravel) + parseInt(this.confood) + parseInt(this.conextras)
                this.conhotel = 'thank you'
                this.contravel = 'now please'
                this.confood = 'fill out the'
                this.conextras = 'life expenses'
            },
            homemath: function () {
                this.hometotal = (parseInt(this.rent) + parseInt(this.food) + parseInt(this.vehicle) + parseInt(this.entertainment)) * 12
                this.rent = 'the total'
                this.food = 'includes'
                this.vehicle = 'the monthly'
                this.entertainment = 'multiplied by 12'
                this.totalmath()
            },
            totalmath: function () {
                this.leftover = this.contotal + this.hometotal
            },
            cosplaymoney: function () {
                this.cosplaymonies = parseInt(this.money) - this.leftover
            }
        }
    })

    const app = new Vue({
        el: "#calculator",
        delimiters: ['[[', ']]'],
        data: {
            user: [],
            csrf_token: "",
            money: '',
        },      
        methods: {
            loadCurrentUser: function() {
                axios({
                    method: 'get',
                    url: '/apis/v1/currentuser/'
                }).then(response => {
                    this.user = response.data
                })
            }
        },
        created: function () {
            this.loadCurrentUser()
        },
        mounted: function () {
            this.csrf_token = document.querySelector("input[name=csrfmiddlewaretoken]").value
        },
    })

    let ctx = document.getElementById('myChart').getContext('2d');
    let labels = ['Typical Hotel 🏢', 'Typical Travel ✈', 'Typical Food 🍕', 'Typical Extras 👕🍣'];
    let colorHex = ['#FB3640', '#EFCA08', '#43AA8B', '#253D5B'];
    
    let myChart = new Chart(ctx, {
        type: 'pie',
        data: {
            datasets: [{
                data: [900, 200, 200, 400],
                backgroundColor: colorHex
        }],
        labels: labels
        },
        options: {
        responsive: true,
        legend: {
            position: 'bottom'
        },
        plugins: {
            datalabels: {
                color: '#fff',
                anchor: 'end',
                align: 'start',
                offset: -10,
                borderWidth: 2,
                borderColor: '#fff',
                borderRadius: 25,
                backgroundColor: (context) => {
                    return context.dataset.backgroundColor;
            },
            font: {
                weight: 'bold',
                size: '10'
            },
            formatter: (value) => {
                return value + ' %';
            }
            }
        }
        }
    })

</script>
</body>

templates/events.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Anton&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'main.css' %}">
    <title>Events</title>
</head>

<body>
{% csrf_token %}
{% if user.is_authenticated %}
    <header class="header">
        <h1>Welcome to Kosupure, {{ user.username }}!</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
        <hr class="tophr">
    </header>
    <span><a style="font-size: 1.5em" href="{% url 'logout' %}">Logout</a></span>
{% else %}
    <header class="header">
        <h1>Welcome to Kosupure, visitor!</h1>
        <h1>You are not logged in.</h1> 
        <h2>
            <a href="{% url 'home' %}">Cosplay Corner</a>
            <a href="{% url 'events' %}">Events</a>
            <a href="{% url 'board' %}">LiveChat</a>
            <a href="{% url 'calculator' %}">Calculator</a>
        </h2>
    </header>
    <span><a href="{% url 'login' %}">Login</a> <a href="{% url 'users:signup' %}" >Sign Up</a></span>
{% endif %}

<div id="events">
    <div v-if="user.is_creator">
    <new-event class="container" :user="user" :csrf_token="csrf_token" @event-created="afterEventCreated()"></new-event>
    </div>
    <br><br>
    <div v-for="event in events" :key="events.id">
        <div class="flex-container">
            <div class="events">   
                <h3>Event Name: [[ event.name ]] </h3>
                <h4>[[ formattingDates(event.date) ]] </h4>
                <h4>[[ event.description ]] </h4>
                <hr>
                <button-attend :user="user" :events="event" :csrf_token='csrf_token' @event-attend="afterEventAttend()"></button-attend>
                <div v-if="event.posted_by.username == user.username">
                    <button @click="deleteEvent(event)" class="delete">Delete Event</button>
                </div>
                <span> Contact [[ event.posted_by.username ]] for more details </span>
                <event-comment-section :user="user" :event='event' :csrf_token='csrf_token' @event-comment-posted="afterEventCommentPosted()"></event-comment-section>
            </div>
        </div>
    </div>

</div>
<script src="https://s3-us-west-2.amazonaws.com/s.cdpn.io/16327/gsap-latest-beta.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script>

Vue.component('new-event', {
    delimiters: ['[[', ']]'],
    props: [ 'user', 'csrf_token' ],
    data: function () {
        return {
        name:  '',
        date: '',
        description: '',
    }},
    template: `
    <form enctype="multipart/form-data">
        <textarea cols="75" rows="1" placeholder="Enter name of event" v-model="name" required></textarea><br>
        <textarea cols="75" rows="3" placeholder="Enter description of event here" v-model="description"></textarea><br>
        <span class="limiter">[[ charactersLeft ]]</span><br>
        <input type="datetime-local" placeholder="Date" v-model="date">
        <button @click.prevent="newEvent" class="submit">Submit</button>
    </form>
    `,
    methods: {
        onFileChanged (event) {
            console.log(event)
            this.selectedFile = event.target.files[0]
        },
        newEvent: function () {
            {% comment %} console.log(this.date)
            let date = new Date(this.date)
            console.log(date) {% endcomment %}
            let formData = new FormData()
            formData.append('user', this.user.id)
            formData.append('name', this.name)
            formData.append('description', this.description)
            formData.append('date', this.date)
            axios({
                method: 'post',
                url: '/apis/v1/events/',
                headers: {
                    'X-CSRFToken': this.csrf_token
                },
                data: formData
            }).then(response => {
                this.name = ''
                this.description = ''
                this.$emit("event-created")
            })
        }
    },
    computed: {
        charactersLeft: function () {
            let char = this.description.length, limit = 300
            return (limit - char) + " / " + limit + " " + "characters remaining"
        }
    }
})

Vue.component('event-comment-section', {
    delimiters: ['[[', ']]'],
    props: [ 'user', 'event', 'csrf_token'],
    data: function () {
        return {
        currentPage: 1,
        maxPerPage: 3,
        currentComment: '',
        }
    },
    template: `
    <div>
        <div v-for="eventcomment in paginatedEventComments" :key="eventcomment.id"> 
            <div class="flex-container">
                <div>[[ eventcomment.event_username.username ]] says:</div>
            </div>
            <div class="flex-container">
                <i><div>[[ eventcomment['event_comment'] ]]</div></i>
                <div>[[ formattingDates1(eventcomment.event_comment_date) ]]</div>
            </div>
            <div v-if="eventcomment.event_username.username == user.username">
                <button @click="deleteComment(eventcomment)" class="delete">Delete Comment</button>
            </div> 
            <br>
        </div>
        <div v-if="currentPage * maxPerPage < event.comments.length"><button @click="loadMore" >load more</button></div>
        <div v-if="user.id">
            <textarea cols="50" rows="2" v-model="currentComment" 
            placeholder="Comments go here (max length 600 characters)" 
            v-on:keyup.enter="submitComment(eventcomment)"></textarea>
            <br>
            <span class="limiter">[[ charactersLeft ]]</span>
            <button @click="submitComment(eventcomment)" class="submit">Submit</button>
        </div>
    </div>
    `,
    methods: {
        loadMore() {
            this.currentPage += 1
        },
        deleteComment: function (eventcomment) {
            axios({
                method: 'delete',
                url: `/apis/v1/eventscomments/${eventcomment.id}/`,
                headers: {
                    'X-CSRFToken': this.csrf_token
                },
            }).then(response => {
                this.$emit("event-comment-posted")
            })
        },
        formattingDates1: function (date) {
            let dateObj = new Date(date)
            let options = { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }
            let newformat=dateObj.toLocaleString('en-US', options)
            return newformat
        },
        submitComment: function (post) {
            axios({
                method: 'post',
                url: '/apis/v1/eventscomments/',
                headers: {
                    'X-CSRFToken': this.csrf_token
                },
                data: {
                        "events": this.event.id,
                        "events_user": this.user.id,
                        "event_comment": this.currentComment,
                }
            }).then(response => {
                this.currentComment = ''
                this.$emit("event-comment-posted")
            })
        },
    },
    computed: {
        paginatedEventComments: function () {
            return this.event.comments.slice(0, this.currentPage * this.maxPerPage)
        },
        charactersLeft: function () {
            let char = this.currentComment.length, limit = 600
            return (limit - char) + " / " + limit + " " + "characters remaining"
        }
    }
})

Vue.component('button-attend', {
    delimiters: ['[[', ']]'],
    props: [ 'user', 'csrf_token', 'events' ],
    data: function () {
        return {
        attend: [],
        }
    },
    template: `
    <div class='flex-container'>
        <div @click="submitAttend" class="heartbutton1"> 🧑‍🤝‍🧑 Going: [[ countattend ]] 🧑‍🤝‍🧑</div>
        <div class="attending"> 🧑‍🤝‍🧑 Users Going: <template v-for="attend in events.attending_details"> [[ attend.username ]], </template></div>
    </div>
    `,
    methods: {
    submitAttend: function() {
        console.log(events)
        if (this.user.attending_events.includes(this.events.id)){
            this.user.attending_events.splice(this.user.attending_events.indexOf(this.events.id),1)
        } else {
            this.user.attending_events.push(this.events.id)
        }
        axios({
            method: 'patch',
            url: `/apis/v1/users/${this.user.id}/`,
            headers: {
                'X-CSRFToken': this.csrf_token
            },
            data: {
                "attending_events": this.user.attending_events,
            }
        }).then(response => {
            this.attend = response.data
            this.$emit("event-attend")
        })
    },
    },
    computed: {
        countattend: function () {
            if (!(this.events.attending_details === [])){
                return this.events.attending_details.length
        }}
    }
})

    const app = new Vue({
        el: "#events",
        delimiters: ['[[', ']]'],
        data: {
            events: [],
            user: [],
            csrf_token: "",
        },      
        methods: {
            loadCurrentUser: function() {
                axios({
                    method: 'get',
                    url: '/apis/v1/currentuser/'
                }).then(response => {
                    this.user = response.data
                })
            },
            loadEvents: function () {
                axios({
                    method: 'GET',
                    url: '/apis/v1/events/'
                }).then(response => {
                    this.events = response.data.reverse()
                    console.log(events)
                })
            },
            deleteEvent: function (event) {
                axios({
                    method: 'delete',
                    url: `/apis/v1/events/${event.id}/`,
                    headers: {
                        'X-CSRFToken': this.csrf_token
                    },
                }).then(response => {
                    this.loadEvents()
                })
            },
            afterEventCreated: function () {
                this.loadEvents()
            },
            afterEventAttend: function () {
                this.loadEvents()
            },
            afterEventCommentPosted: function () {
                this.loadEvents()
            },
            formattingDates: function (date) {
                let dateObj = new Date(date)
                let options = { weekday: 'short', year: 'numeric', month: 'short', day: 'numeric', hour: 'numeric', minute: 'numeric' }
                let newformat=dateObj.toLocaleString('en-US', options)
                console.log(typeof(dateObj))
                return newformat
            },
        },
        created: function () {
            this.loadEvents()
            this.loadCurrentUser()
            this.loadEventsComments()
        },
        mounted: function () {
            this.csrf_token = document.querySelector("input[name=csrfmiddlewaretoken]").value
        },
    })

</script>
</body>